# Generated by Django 5.0.4 on 2024-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_subject_group_subject_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='subject',
        ),
        migrations.AddField(
            model_name='grades',
            name='grades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
